name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install
      - run: ./vendor/bin/php-cs-fixer check
      - run: ./vendor/bin/phpstan
      - run: ./vendor/bin/phpunit
